vs060:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: j1
    pid: {p: 10000.0, i: 500.0, d: 200.0, i_clamp: 100.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: j2
    pid: {p: 100.0, i: 50.0, d: 20.0, i_clamp: 100.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: j3
    pid: {p: 1500.0, i: 500.0, d: 100.0, i_clamp: 100.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: j4
    pid: {p: 100.0, i: 500.0, d: 20.0, i_clamp: 100.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: j5
    pid: {p: 100.0, i: 10.0, d: 10.0, i_clamp: 0.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: flange
    pid: {p: 100, i: 0.0, d: 0.0, i_clamp: 0.0}
