language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false
script: source .travis/travis.sh
