language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=groovy ROSWS=wstool BUILDER=catkin    USE_DEB=true
  - ROS_DISTRO=groovy ROSWS=wstool BUILDER=catkin    USE_DEB=false
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false
  - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true
  - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false
matrix:
  allow_failures:
    - env: ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true
    - env: ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false
script: source .travis/travis.sh
